#!/usr/bin/env sh

#$1 is the battery instance

instance=0
if [ $# -gt 0 ]; then
  instance=$1
fi

capacity=$(cat /sys/class/power_supply/BAT${instance}/capacity)
status=$(cat /sys/class/power_supply/BAT${instance}/status)

class="DIS"
icon=' '
if [ "${capacity}" -gt 75 -a "${capacity}" -le 100 ]; then
  icon=' '
elif [ "${capacity}" -gt 50 -a "${capacity}" -le 75 ]; then
  icon=' '
elif [ "${capacity}" -gt 25 -a "${capacity}" -le 50 ]; then
  icon=' '
elif [ "${capacity}" -gt 15 -a "${capacity}" -le 25 ]; then
  icon=' '
elif [ "${capacity}" -lt 15 ]; then
  class="CRI"
fi

if [ $status = "Charging" ]; then
  class="CHR"
elif [ $status = "Full" ]; then
  class="FULL"
elif [ $status = "Unknown" ]; then
  class="UNK"
fi

time=$(acpi -b | awk -v acpi_bat_num=$((instance + 1)) 'NR == acpi_bat_num {print $5}')

if [ "${#time}" -eq 0 ]; then
  time="-"
fi

printf '{"text":"%s","tooltip":"%s%% (%s)","class":"%s","percentage":%s}\n' \
  $icon $capacity $time $class $capacity

