#!/usr/bin/env sh

#$1 is the battery instance

[[ ! -z $1 ]] && instance=$1 || instance=0

capacity=$(cat /sys/class/power_supply/BAT${instance}/capacity)
status=$(cat /sys/class/power_supply/BAT${instance}/status)

class="DIS"
((capacity > 75 && capacity <=100)) && icon=' '
((capacity > 50 && capacity <=75)) && icon=' '
((capacity > 25 && capacity <=50)) && icon=' '
((capacity > 15 && capacity <=25)) && icon=' '
((capacity <= 15)) && icon=' ' && class="CRI"

if [ $status = "Charging" ]; then
    class="CHR"
elif [ $status = "Full" ]; then
    class="FULL"
elif [ $status = "Unknown" ]; then
    class="UNK"
fi
time=$(acpi -b | awk -v acpi_bat_num=$((instance + 1)) \
  'NR == acpi_bat_num {print $5}')
(( ${#time} == 0 )) && time="-"

printf '{"text":"%s","tooltip":"%s%% (%s)","class":"%s","percentage":%s}\n' \
  $icon $capacity $time $class $capacity

