#!/bin/bash

#$1 is the battery instance

[[ ! -z $1 ]] && battery_instance=$1 || battery_instance=0

battery_capacity=$(cat /sys/class/power_supply/BAT${battery_instance}/capacity)
battery_status=$(cat /sys/class/power_supply/BAT${battery_instance}/status)
if [ $battery_status = "Full" ]; then
    icon=' ' && class="FULL"
elif [ $battery_status = "Unknown" ]; then
    icon=' ' && class="UNK"
elif [ $battery_status = "Charging" ]; then
    icon=' ' && class="CHR"
elif [ $battery_status = "Discharging" ]; then
    ((battery_capacity <= 15)) &&
        icon=' ' && class="CRI"
    ((battery_capacity > 15 && battery_capacity <=25)) &&
        icon=' ' && class="DIS"
    ((battery_capacity > 25 && battery_capacity <=50)) &&
        icon=' ' && class="DIS"
    ((battery_capacity > 50 && battery_capacity <=75)) &&
        icon=' ' && class="DIS"
    ((battery_capacity > 75 && battery_capacity <=100)) &&
        icon=' ' && class="DIS"
fi
battery_time=$(acpi -b | awk -v acpi_bat_num=$((battery_instance + 1)) 'NR == acpi_bat_num {print $5}')
(( ${#battery_time} == 0 )) && battery_time="-"

printf '{"text":"%s","tooltip":"%s%% (%s)","class":"%s","percentage":%s}\n' $icon $battery_capacity $battery_time $class $battery_capacity

