#!/bin/bash

volume=$(amixer sget Master | grep % | awk -F '[][]' '{ print $2 }')
volume=${volume%\%}
muted=$(amixer sget Master | grep % | awk -F '[][]' '{ print $6 }')

(( volume > 1 )) && icon=
(( volume > 33 )) && icon=
(( volume > 66 )) && icon=
(( volume <= 1 )) || [[ $muted == 'off' ]] && icon=

echo $volume $icon

