#!/usr/bin/env sh

volume=$(amixer sget Master | awk -F '[][]' 'BEGIN { RS="" } { print $2 }')
volume=${volume%\%}
muted=$(amixer sget Master | awk -F '[][]' 'BEGIN { RS="" } { print $6 }')

(( volume > 1 )) && icon=
(( volume > 20 )) && icon=
#(( volume > 50 )) && icon=
(( volume > 90 )) && icon=
(( volume <= 1 )) || [[ $muted == 'off' ]] && icon=

printf '{"text":"%s","tooltip":"%s%%","class":"%s","percentage":%s}\n' $icon $volume $muted $volume

