#!/bin/bash

volume=$(amixer sget Master | awk -F '[][]' '/[0-9]{1,3}%/ {print $2}')
volume=${volume%\%}
muted=$(amixer sget Master | awk -F '[][]' '/[0-9]{1,3}%/ { print $6 }')

(( volume > 1 )) && icon=
(( volume > 33 )) && icon=
#(( volume > 66 )) && icon=
(( volume > 90 )) && icon=
(( volume <= 1 )) || [[ $muted == 'off' ]] && icon=

printf '{"text":"%s","tooltip":%s,"class":"%s","percentage":%s}\n' $icon $volume $muted $volume

